
// í•œ ì”¬ë‹¹ í…ìŠ¤íŠ¸ íŒŒì¼ì€ í•˜ë‚˜ë¡œ ëë‚´ì!!!
// 
// ===========================================
// ğŸ“Œ [ëŒ€ì‚¬ íŒŒì¼ êµ¬ì¡° ì„¤ëª…]
// ===========================================
// ê° ì¤„ì€ í•˜ë‚˜ì˜ ëŒ€ì‚¬ë¥¼ ì˜ë¯¸í•˜ë©°, "|"ë¡œ êµ¬ë¶„ëœ ì—¬ëŸ¬ ê°œì˜ í•„ë“œë¥¼ í¬í•¨í•¨
// í•„ë“œë³„ ì—­í•  ë° ë°ì´í„° í˜•ì‹ ì„¤ëª…ì€ ì•„ë˜ì™€ ê°™ìŒ
//
//
//ğŸ“œ ëŒ€ì‚¬ íŒŒì¼ êµ¬ì¡°
//
//
//í™”ì|ëŒ€í™”ë‚´ìš©|ìºë¦­í„° ì´ë¯¸ì§€|íš¨ê³¼ìŒ|ìŒì„±|ë°°ê²½ìŒ|ë°±ê·¸ë¼ìš´ë“œì´ë¯¸ì§€|ì„ íƒì§€id|ì• ë‹ˆë©”ì´ì…˜í‚¤ì›Œë“œ
// ë°°ê²½ ì´ë¯¸ì§€ ë³€ê²½ì€ VariableManagerì—ì„œ ì²˜ë¦¬(ì´ìœ ëŠ” ìŠ¤í¬ë¦½íŠ¸ ë³¼ë¥¨, ë°°ê²½ ì´ë¯¸ì§€ ì‚¬ìš© ë¹ˆë„ ë‚®ìŒ)
//
// [í•„ë“œ 1] í™”ì ì´ë¦„
//   - ëŒ€ì‚¬ë¥¼ ë§í•˜ëŠ” ìºë¦­í„°ì˜ ì´ë¦„ì„ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "ìœ  ì´ì—°"
//
// [í•„ë“œ 2] ëŒ€ì‚¬ ë‚´ìš©
//   - ìºë¦­í„°ê°€ ì¶œë ¥í•  ëŒ€ì‚¬ ë¬¸ìì—´ì…ë‹ˆë‹¤.
//   - ëŒ€ì‚¬ ë‚´ì—ì„œ íŠ¹ì • íƒœê·¸ë¥¼ ì‚¬ìš©í•˜ì—¬ ë‹¤ì–‘í•œ ì—°ì¶œ íš¨ê³¼ë¥¼ ì ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
//
//   ğŸ”¹ íŠ¹ìˆ˜ íƒœê·¸ ì„¤ëª…
//   ---------------------------------------------------------
//   (end) : ê³µí†µì ìœ¼ë¡œ ì ìš©ë©ë‹ˆë‹¤. íƒœê·¸ê°€ ëë‚¬ë‹¤ëŠ” ê²ƒì„ ì˜ë¯¸í•©ë‹ˆë‹¤.
//   r : ì‚¬ì´ì¦ˆ ê´€ë ¨ ë³€ìˆ˜ì— ì ìš©ë©ë‹ˆë‹¤. ê¸°ë³¸ê°’ìœ¼ë¡œ ë˜ëŒë¦½ë‹ˆë‹ˆë‹¤.
//
//   *N  : ë³¼ë¥¨ ì¡°ì ˆ (0~1 ì‚¬ì´ ê°’, ì˜ˆ: *0.5 ë³¼ë¥¨ ë‚®ì¶¤, *1 ì›ë˜ ë³¼ë¥¨)
//   #N  : ë³´ì´ìŠ¤ í”¼ì¹˜ ì¡°ì ˆ (-3~3 ì‚¬ì´ ê°’, ì˜ˆ: #0.03 í”¼ì¹˜ ì¦ê°€, #-0.03 í”¼ì¹˜ ê°ì†Œ)
//   \N  : ì¶œë ¥ ì†ë„ ë³€ê²½ (ì˜ˆ: \2 -> ì†ë„ 2ë°° ë¹ ë¥´ê²Œ)
//          * \r : ì›ë˜ëŒ€ë¡œ
//   $N  : ì¶œë ¥ ëŒ€ê¸° ì‹œê°„ (ì˜ˆ: $0.5 -> 0.5ì´ˆ í›„ ë‹¤ìŒ ê¸€ì ì¶œë ¥)
//   ^   : ë„ë• ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
//   %   : ì„ íƒì§€ í‘œì‹œ (í•´ë‹¹ ì¤„ì´ ì„ íƒì§€ íŒ¨ë„ì„ ë„ìš°ë„ë¡ ì²˜ë¦¬)
//   @N  : ë‹¤ì´ì–¼ë¡œê·¸ ì‚¬ì´ì¦ˆë¥¼ Në§Œí¼ìœ¼ë¡œ ë§Œë“­ë‹ˆë‹¤.
//   ---------------------------------------------------------
// [í•„ë“œ 3] ìºë¦­í„° ì´ë¯¸ì§€
//   - ëŒ€ì‚¬ ì§„í–‰ ì¤‘ ë³€ê²½í•  ìºë¦­í„°ì˜ ì´ë¯¸ì§€ íŒŒì¼ëª…ê³¼ ìœ„ì¹˜ë¥¼ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "image_nurse_concept_1, 0000"
//   - 1000 <- ìºë¦­í„°ê°€ ì œì¼ ì™¼ìª½ì— ì„œìˆë‹¤ëŠ” ì˜ë¯¸ê³  0001 <- ìºë¦­í„°ê°€ ì œì¼ ì˜¤ë¥¸ìª½ì— ì„œìˆë‹¤ëŠ” ì–˜ê¹ë‹ˆë‹¤.
//   - 0000 <- ìºë¦­í„°ë¥¼ ì¤‘ì•™ì— ì„¸ì›Œë†“ìŠµë‹ˆë‹¤.
//   - ì£¼ì˜)0000ì€ ìºë¦­í„°ê°€ í•˜ë‚˜ë§Œ ìˆì„ ë•Œë§Œ ë°›ìŠµë‹ˆë‹¤. ì˜ˆì™¸ì²˜ë¦¬ ì•ˆ ë˜ì–´ ìˆìœ¼ë‹ˆ(ì•„ì§) ì£¼ì˜í•©ì‹œë‹¤.
// [í•„ë“œ 4] íš¨ê³¼ìŒ (SE, Sound Effect)
//   - íŠ¹ì • ëŒ€ì‚¬ì—ì„œ ì¬ìƒí•  íš¨ê³¼ìŒ íŒŒì¼ì˜ ì´ë¦„ì„ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "Knock" (Knock.mp3 íŒŒì¼ ì¬ìƒ)
// [í•„ë“œ 5] ìŒì„± (Voice)
//   - ëŒ€ì‚¬ì— ë§ì¶° ì¬ìƒí•  ìŒì„± íŒŒì¼ëª…ì„ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "voice" (voice.mp3 íŒŒì¼ ì¬ìƒ)
//
// [í•„ë“œ 6] ë°°ê²½ ìŒì•… (BGM)
//   - íŠ¹ì • ëŒ€ì‚¬ì—ì„œ ë³€ê²½í•  ë°°ê²½ ìŒì•…ì„ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "downvoice"
// [í•„ë“œ 7] ë°±ê·¸ë¼ìš´ë“œ ì´ë¯¸ì§€
//   - ì„ íƒí•œ ê²ƒì— ë§ëŠ” ë°±ê·¸ë¼ìš´ë“œ ì´ë¯¸ì§€ë¥¼ ì¬ìƒí•©ë‹ˆë‹¤.
//[í•„ë“œ 8] ì„ íƒì§€ ID
//   - íŠ¹ì • ëŒ€ì‚¬ì—ì„œ ì„ íƒì§€ê°€ ë‚˜íƒ€ë‚  ê²½ìš° í•´ë‹¹ ì„ íƒì§€ì˜ IDë¥¼ ì„¤ì •í•©ë‹ˆë‹¤.
//   - ì—†ì„ ê²½ìš° ë¹ˆ ë¬¸ìì—´("")ë¡œ ì„¤ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "1" (ì„ íƒì§€ê°€ ìˆëŠ” ê²½ìš°), "" (ì„ íƒì§€ê°€ ì—†ëŠ” ê²½ìš°)
// [í•„ë“œ 9] ì• ë‹ˆë©”ì´ì…˜ í‚¤ì›Œë“œ
//   - íŠ¹ì • ì• ë‹ˆë©”ì´ì…˜ì„ ì‹¤í–‰í•˜ê¸° ìœ„í•œ í‚¤ì›Œë“œë¥¼ ì§€ì •í•©ë‹ˆë‹¤.
//   - ì˜ˆ: "ë„ë•" (ë„ë•ì´ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰), "ì–´ë‘ " (í™”ë©´ ì–´ë‘ì›Œì§ ë“±) 
//   - CircleFadeOut/In = ì›ìœ¼ë¡œ ì‘ì•„ì§€ëŠ”/ì»¤ì§€ëŠ” íš¨ê³¼ì…ë‹ˆë‹¤. 
//
// ===========================================
// ğŸ”¹ [íŒŒì¼ ì˜ˆì‹œ]
// ===========================================
// ìœ  ì´ì—°|ì§€ê¸ˆ ê¸°ë¶„ì´ ì–´ë– ì„¸ìš”?\1.5$0.5 ì–´ë”” ì•„í”ˆ ê³³ì€\0.5 ì—†ë‚˜ìš”?||image_nurse_concept_1||voice|ê°„í˜¸ì‚¬_ê¸°ë³¸|
// ìœ  ì´ì—°|ê´œì°®ì•„ìš”.$1 ì²œì²œíˆ ìˆ¨ ì‰¬ì„¸ìš”.\2.5$0.5 ê¹Šê²Œ*0 ...$0.5 *1ì²œì²œíˆ*0 ...||image_nurse_concept_1||downvoice||
// ìœ  ì´ì—°|*1ê·¸ëŸ¼,$0.5 ì˜¤ëŠ˜ë„ í‰ë²”í•œ í•˜ë£¨ë¥¼ ë³´ë‚´ë„ë¡ í•´ìš”.|Knock|image_nurse_concept_1||voice||ë„ë•|ì–´ë‘ 
//
// ===========================================
// ğŸ”¹ [ì¶”ê°€ ì‚¬í•­]
// ===========================================
// - ëŒ€ì‚¬ íŒŒì¼ì„ ìˆ˜ì •í•  ë•Œ, íƒœê·¸ ì‚¬ìš© ì‹œ ì£¼ì˜í•´ì•¼ í•©ë‹ˆë‹¤.
// - ê° í•„ë“œëŠ” "|" êµ¬ë¶„ìë¡œ ë‚˜ë‰˜ë©°, ê°œìˆ˜ê°€ ë§ì§€ ì•Šì„ ê²½ìš° ì˜¤ë¥˜ê°€ ë°œìƒí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
// - íƒœê·¸ë¥¼ ì˜¬ë°”ë¥´ê²Œ ì‚¬ìš©í•˜ì—¬ ì—°ì¶œì„ í’ë¶€í•˜ê²Œ ë§Œë“¤ ìˆ˜ ìˆìŠµë‹ˆë‹¤.
//
// ===========================================
//  ì•„ë˜ ìŠ¤í¬ë¦½íŠ¸ëŠ” ëŒ€ì‚¬ íŒŒì¼ì„ ê´€ë¦¬í•˜ëŠ” ë‹¤ì´ì–¼ë¡œê·¸ ë§¤ë‹ˆì €ì…ë‹ˆë‹¤.
//  íŒŒì¼ ë§¤ë‹ˆì €, í…ìŠ¤íŠ¸ì• ë‹ˆë©”ì´ì…˜ìŠ¤í¬ë¦½íŠ¸, ì„ íƒì§€ë§¤ë‹ˆì €ì™€ ìƒì†ê´€ê³„ì´ë¯€ë¡œ í•¨ë¶€ë¡œ ìˆ˜ì •í•˜ì§€ ë§ ê²ƒ
//

//
//ì˜ˆìƒë˜ëŠ” ì˜¤ë¥˜ ì‚¬í•­ : ë§Œì•½ì— ì„ íƒì§€ê°€ ì—°ì†ìœ¼ë¡œ ë‘ê°œ ëœ¨ëŠ” ìƒí™©ì´ë©´?
// ===========================================
using System.Collections;
using UnityEngine;
using TMPro;
using UnityEngine.UI;
using System.IO;
using System;
using System.Text.RegularExpressions;
using JetBrains.Annotations;
using System.Collections.Generic;
using UnityEditor.EditorTools;
using System.Data.Common;
using System.Linq.Expressions;
using System.Runtime.CompilerServices;
using UnityEditor;
using UnityEditor.ShaderKeywordFilter;
using System.Diagnostics.Tracing;


public class DialogueManager : MonoBehaviour
{
    [Header("íŒŒì¼ ë§¤ë‹ˆì € (Inspectorì—ì„œ ì§€ì •)")]
    public FileManager fileManager;
    public GameObject FileManagerObj;
    [Tooltip("ì´ ì”¬ì—ì„œ ì‚¬ìš©í•  í…ìŠ¤íŠ¸ íŒŒì¼ ì´ë¦„")]
    public string TextFileNameThisScene;

    [Header("ì‚¬ìš´ë“œ ë§¤ë‹ˆì €(Insperctorì—ì„œ ì§€ì •)")]
    public SoundManager soundManager;
    public GameObject soundManagerObj;

    [Header("ì´ë¯¸ì§€ ë§¤ë‹ˆì €(ì¸ìŠ¤í™í„°ì—ì„œ ì§€ì •)")]
    public CharacterImageManager characterImageManager;
    public GameObject characterImageManagerObj;
    public BackGroundManager backGroundManager;
    public GameObject backgroundManagerObj;

    [Header("ì„ íƒì§€ ë§¤ë‹ˆì € (Inspectorì—ì„œ ì§€ì •)")]
    public ChoiceManager choiceManager; // âœ… ì„ íƒì§€ ë§¤ë‹ˆì € ì—°ê²°
    public GameObject choiceManagerObj;
    public bool hasChoice = false; // ì„ íƒì§€ê°€ ì¡´ì¬í•©ë‹ˆê¹Œ?
    [Header("íŠ¸ëœì§€ì…˜ ë§¤ë‹ˆì €")]
    public TransitionShaderController transitionShaderController;
    public GameObject transitionControllerobj;

    [Header("UI ìš”ì†Œë“¤")]
    public TMP_Text speakerText;
    public TMP_Text DialogueText;
    public Image TextBox;

    [Header("í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ì„¤ì •")]
    [Range(0f, 0.1f)] public float defaultDelay = 0.05f;


    [Header("í…Œí¬ë‹ˆì»¬í•œ ë³€ìˆ˜ë“¤ ì €ì¥ë˜ëŠ” ê³³ - í…ŒìŠ¤íŠ¸ ëë‚˜ë©´ ë‹¤ privateë¡œ ë³€ê²½")]


    [Tooltip("í…ìŠ¤íŠ¸ë¥¼ ì¶œë ¥í•  ì¤€ë¹„ê°€ ëëŠ”ì§€ í™•ì¸")]
    public bool isDialogueReady = false;
    //ì–˜ê°€ true ìƒíƒœì—¬ì•¼ updateì—ì„œ í´ë¦­ì„ ê°ì§€í•¨.
    //ë˜í•œ ì–˜ê°€ trueì¸ì§€ ê²€ì‚¬í•´ì„œ ì‘ë™ì‹œí‚¤ëŠ” í•¨ìˆ˜ë„ í•„ìš”í•  ê²ƒ ê°™ê¸´ í•œë° í˜„ì¬ë¡œì„  ëª¨ë¥´ê²ƒë‹¤.

    [Tooltip("ì§€ê¸ˆ í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ì´ ì‘ë™ì¤‘ì¸ì§€ í™•ì¸.")]
    public bool isTyping = false;
    //ì–˜ê°€ true ìƒíƒœë¼ë©´ ìŠ¤í‚µì„ ì‘ë™ì‹œí‚´. 

    [Tooltip("í˜„ì¬ ì½ê³  ìˆëŠ” ì¸ë±ìŠ¤")]
    public int currentIndex = 0;
    [Tooltip("ì„ íƒì§€ íŒ¨ë„ í™œì„±í™” ì—¬ë¶€")]
    public bool isChoicePanelActive = false; // ì„ íƒì§€ íŒ¨ë„ í™œì„±í™” ì—¬ë¶€

    [Tooltip("í˜„ì¬ ì½ê³  ìˆëŠ” íŒŒì¼ì˜ ì¸ë±ìŠ¤ê°€ ëë‚¬ëŠ”ì§€ ì—¬ë¶€")]
    public bool isThisSceneTextFileEnd = false;

    [Tooltip("ìŠ¤í‚µí• ì§€ ì•ˆí• ì§€ í™•ì¸")]
    public bool isSkipTextAnimation = false;//ì´ê²Œ trueë©´ updateê°€ ì‘ë™í•˜ì§€ ì•ŠìŒ. 

    [Header("ê¸°ë³¸ê°’ ë³€ìˆ˜ë“¤ ì €ì¥ë˜ëŠ” ê³³")]

    [Tooltip("ê¸°ë³¸ ë‹¤ì´ì–¼ë¡œê·¸ í…ìŠ¤íŠ¸ ì‚¬ì´ì¦ˆ ì €ì¥ë˜ëŠ” ê³³.")]
    public float defaultDialogueTextSize;
    [Tooltip("ê¸°ë³¸ í™”ì í…ìŠ¤íŠ¸ ì‚¬ì´ì¦ˆ ì €ì¥ë˜ëŠ” ê³³.")]
    public float defaultSpeakerTextSize;

    [Tooltip("ìŠ¤í‚µì´ í•„ìš”í•œì§€ ì•ˆ í•„ìš”í•œì§€ ë§í•˜ëŠ” ê³³")]
    public bool isSkiping = false;

    [Tooltip("í´ë¦­í–ˆëŠ”ì§€ ì•ˆ í–ˆëŠ”ì§€ í™•ì¸")]
    public bool isClickDialogueBox;

    [Tooltip("ì „ì²´ í…ìŠ¤íŠ¸")]
    public string LinefullText;
    public int remainTextAmout;

    [Tooltip("ì½”ë£¨í‹´")]
    public IEnumerator TextAnimationCor;
    [Tooltip("íŠ¸ëœì§€ì…˜ì¤‘ì¸ì§€ ì•„ë‹Œì§€ í™•ì¸")]
    
    public bool isTrandition = false;

    [Tooltip("ë¶„ê¸°ë¥¼ íƒí•´ì•¼ í•˜ëŠ”ì§€ ì—¬ë¶€ í™•ì¸")]
    public bool HavetoTakeBranch = false;
    public int SeleceBranchStartIndex = 0;//ì‹œì‘ ì¸ë±ìŠ¤
    public int SelectBranchEndIndex = 0;//ë ì¸ë±ìŠ¤
    public int SelectBranchDestindex = 0;//ë§ˆì§€ë§‰ ì¸ë±ìŠ¤


    void Awake()
    {
        /*
        [Awake ë¡œì§]
        1. ê° ë§¤ë‹ˆì €ë“¤ ê³µí†µ ë¡œì§ - ë§¤ë‹ˆì € ì˜¤ë¸Œì íŠ¸ / ì»´í¬ë„ŒíŠ¸ ì—°ê²°.  
        */
        GetAllManagerComponents();//ì»´í¬ë„ŒíŠ¸ ì—°ê²°

    }

    /// <summary>
    /// ì „ì²´ ë§¤ë‹ˆì €ë“¤ ì˜¤ë¸Œì íŠ¸ì—ì„œ ì»´í¬ë„ŒíŠ¸ë¥¼ ë¹¼ì„œ ì—°ê²°í•´ì¤ë‹ˆë‹¤. 
    /// </summary>
    private void GetAllManagerComponents()
    {
        CheckManagerAndAssignComp(FileManagerObj, out fileManager, "FileManager");
        CheckManagerAndAssignComp(soundManagerObj, out soundManager, "SoundManager");
        CheckManagerAndAssignComp(characterImageManagerObj, out characterImageManager, "CharacterImageManager");
        CheckManagerAndAssignComp(choiceManagerObj, out choiceManager, "ChoiceManager");
        CheckManagerAndAssignComp(backgroundManagerObj, out backGroundManager, "BackGroundManager");
    }
    /// <summary>
    /// ì „ì²´ ë§¤ë‹ˆì €ë¥¼ ì²´í¬í•˜ê³  ì»´í¬ë„ŒíŠ¸ì™€ ì´ì–´ì£¼ëŠ” ì—­í• . 
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="obj"></param>
    /// <param name="manager"></param>
    /// <param name="managerName"></param>
    private void CheckManagerAndAssignComp<T>(GameObject obj, out T manager, string managerName) where T : Component
    {
        if (obj != null && obj.TryGetComponent(out manager)) return;

        manager = null;
        Debug.LogError($"[GetAllManagerComponents] {managerName}ê°€ nullì…ë‹ˆë‹¤! ({obj?.name ?? "NULL"})");
    }


    void Start()
    {
        /*[Start ë¡œì§]]

        1. íŒŒì¼ ë§¤ë‹ˆì € ì´ˆê¸°í™” - í˜„ì¬ íŒŒì¼ ì„¤ì •
        2. default ì‹œë¦¬ì¦ˆ ë³€ìˆ˜ ì´ˆê¸°í™”
        3. ì¶œë ¥ ì¤€ë¹„
        */

        //í˜„ì¬ íŒŒì¼ ì„¤ì •. 
        if (!fileManager.TextFileNameSet.Contains(TextFileNameThisScene))
        {
            //ë§Œì•½ ê·¸ëŸ° íŒŒì¼ ì—†ìŠµë‹ˆë‹¤ íŒì •ì´ ë‚˜ì˜¤ë©´
            Debug.LogError($"[Start]ì—ì„œì˜ ì˜¤ë¥˜ : {TextFileNameThisScene}ì´ filemanagerì— ì¡´ì¬í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤!");
            //ì—†ìŠµë‹ˆë‹¤ ë”± ë–„ë ¤ì£¼ê³ 
        }
        else
        {
            fileManager.SetCurrentFile(TextFileNameThisScene);
            //ìˆë‹¤ ì‹¶ìœ¼ë©´ ë°”ë¡œ í˜„ì¬íŒŒì¼ë¡œ ì„¤ì •
        }

        //ê¸°ë³¸ê°’ ë³€ìˆ˜ ì„¤ì •
        AssignAlldefaultVariable();

        //ì¶œë ¥ ì¤€ë¹„.
        StartShowDialogue();
    }
    void AssignAlldefaultVariable()
    {
        defaultDialogueTextSize = DialogueText.fontSize;
        defaultSpeakerTextSize = speakerText.fontSize;

    }

    void Update()
    {
        if (!isDialogueReady) return;//ì¤€ë¹„ ì•ˆ ëì„ ê²½ìš° ë¹ ê¾¸
        else if (isChoicePanelActive) return;//ì„ íƒì§€ ì¼œì ¸ìˆì–´ë„ ë¹ ê¾¸
        else if (isSkipTextAnimation) return;//ìŠ¤í‚µ ì¤‘ì´ì–´ë„ ë¹ ê¾¸
        else if (isTrandition) return;
        //ë‘˜ ë‹¤ ë›°ì–´ë„˜ì—ˆì„ ê²½ìš°. ê·¸ëŸ¬ë‹ˆê¹Œ ì„ íƒì§€ë„ ì•ˆ ì¼œì ¸ ìˆê³  ë‹¤ì´ì–¼ë¡œê·¸ë¡œ ë ˆë””ì¼ ë•Œ. 
        //ì—…ë°ì´íŠ¸ì™€ ê¸°ì¡´ í•¨ìˆ˜ëŠ” ë³‘ë ¬ì ìœ¼ë¡œ ì ìš©ë˜ëŠ”ê°€?
        if (Input.GetKeyDown(KeyCode.Space) || isClickDialogueBox)
        {
            Debug.Log("ìŠ¤í˜ì´ìŠ¤ë°” / UIì— ë§ˆìš°ìŠ¤ í´ë¦­ ê°ì§€. ë„˜ì–´ê°‘ë‹ˆë‹¤.");
            //ìŠ¤í˜ì´ìŠ¤ë¥¼ í´ë¦­í•˜ê±°ë‚˜, UIClickEventScriptsì—ì„œ ê°’ì„ trueë¡œ ë°”ê¾¸ë©´ ì—¬ê¸°ì„œ ë°˜ì‘.
            if (isTyping) // í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ì¤‘ì´ë©´ ìŠ¤í‚µ
            {
                isClickDialogueBox = false;
                SkipTypingAnimation();
                
            }
            else
            {
                //ë””ë ‰íŒ… ë§¤ë‹ˆì € ìª½ì—ì„œ checkAllë³€ê²½ì  í•œë²ˆ ëŒë ¤ì„œ ì–´ë–»ê²Œ ë°”ë€Œë‚˜ í…ŒìŠ¤íŠ¸í•˜ê³ . 
                isClickDialogueBox = false;
                currentIndex++;
                ShowNextLine();
            }
        }
    }

    /// <summary>
    /// íƒ€ì´í•‘ ìŠ¤í‚µí•˜ê³  ë°”ë¡œ ì‹¤í–‰ë˜ë„ë¡ ë³€ê²½
    /// </summary>
    public void SkipTypingAnimation()
    {
        isSkipTextAnimation = true;//ìš°ì„  update ìª½ì—ì„œ ì ‘ê·¼ ë§‰ì•„ì£¼ê³ 
        StopCoroutine(TextAnimationCor);
        string remainText = RemoveAllTag(LinefullText.Substring(LinefullText.Length - remainTextAmout));
        Debug.Log(remainText);
        DialogueText.text += remainText;
        isSkipTextAnimation = false;
        isTyping = false;
        Debug.Log("ë¹ ë¥¸ ìŠ¤í‚µ ì§„í–‰.");
        onCompleteTyping();
      
    }

    public void StartShowDialogue()
    {
        currentIndex = 0;
        ShowNextLine();

    }

    public void ShowNextLine()
    {
        isDialogueReady = false;//ë¯¸ë¦¬ ë¸”ë½í•´ì„œ ì…ë ¥ ë°›ì§€ ëª»í•˜ê²Œ í•˜ê¸°.
        if (isChoicePanelActive)
        {
            Debug.LogError("ì•„ë‹ˆ ì„ íƒì§€ê°€ ì¼œì¡ŒëŠ”ë° ì™œ ì–˜ê°€ ì‘ë™í•˜ê³  ìˆëŠ”ê±°ëƒ?");
            return;
        }
        Debug.Log($"âœ… ShowNextLine í˜¸ì¶œ (currentIndex: {currentIndex})");


        // ğŸ”¹ í˜„ì¬ ë°ì´í„° ê°€ì ¸ì˜¤ê¸°
        var data = fileManager.GetRowByIndex(currentIndex);
        // ìœ  ì´ì—°|ì§€ê¸ˆ ê¸°ë¶„ì´ ì–´ë– ì„¸ìš”?\1.5$0.5 ì–´ë”” ì•„í”ˆ ê³³ì€\0.5 ì—†ë‚˜ìš”?%||image_nurse_concept_1|Scene1Choice:0|voice|ê°„í˜¸ì‚¬_ê¸°ë³¸|
        //ëŒ€ì‚¬ íŒŒì¼ì˜ ì˜ˆì‹œ. 

        if (data == null || data.Length == 0)
        {
            Debug.Log($"âš ï¸ ëŒ€ì‚¬ íŒŒì¼ì˜ ë§ˆì§€ë§‰ ì¤„ì— ë„ë‹¬í–ˆìŠµë‹ˆë‹¤. (currentIndex: {currentIndex})");
            return;
        }//ëŒ€ì‚¬ íŒŒì¼ì´ nullì„ ì œê³µí–ˆì„ ê²½ìš° ë§ˆì§€ë§‰ ì¤„ì— ë„ë‹¬í–ˆë‹¤ëŠ” ê²ƒì´ë¯€ë¡œ end of this Sceneì„. 

        //ë¶„ê¸° ì„¤ì •
        if(HavetoTakeBranch){
            if(currentIndex == SelectBranchEndIndex+1){
                //ì„ íƒì§€ì˜ ë‹¤ë¥¸ ë¶„ê¸° ì¤‘ í•˜ë‚˜ì— ë„ë‹¬í–ˆì„ ê²½ìš°
                currentIndex = SelectBranchDestindex;
                HavetoTakeBranch = false;
                ShowNextLine();
                return;
            }else if(!(currentIndex <= SelectBranchEndIndex && currentIndex >=SeleceBranchStartIndex))
            {
                currentIndex = SeleceBranchStartIndex;
                ShowNextLine();
                return;

            }
        }

        // ğŸ”¹ ë°ì´í„° í•„ë“œ ë¶„ë¦¬
         if(data.Length >=9&&!data[8].Trim().Equals("None")){
            transitionControllerobj.SetActive(true);
            //ë¯¸ë¦¬ ì¼œë†“ê³ 
        }

        

        // ğŸ”¹ UI í…ìŠ¤íŠ¸ ì„¤ì •
        string speaker = data[0]?.Trim();//íŒŒì¼ì—ì„œ ì½ì–´ì„œ ì‹¤ì œë¡œ ì ìš©í• , ë§í•˜ëŠ” ì‚¬ëŒ
        speakerText.text = string.IsNullOrEmpty(speaker) ? " " : speaker;//nullì¼ë• nullë¡œ, ì•„ë‹ë• í…ìŠ¤íŠ¸ë¡œ. 

        string dialogue = data[1]?.Trim();//íŒŒì¼ì—ì„œ ì½ì–´ì„œ ì‹¤ì œë¡œ ì ìš©í• , ëŒ€ì‚¬
        LinefullText = dialogue;
        Debug.Log(speaker + dialogue + "ì´ í…ìŠ¤íŠ¸ë“¤ ë„£ìœ¼ë ¤ê³  ì¤€ë¹„ì¤‘ì…ë‹ˆë‹¤.");
        // RemoveDialogueTag(dialogue);//ë‹¤ì´ì–¼ë¡œê·¸ ë°ì´í„° ë‚´ë¶€ íƒœê·¸ ì œê±° -> íƒœê·¸ ì œê±°ëŠ” í•„ìš”í•  ë•Œë§Œ í•˜ëŠ”ê±¸ë¡œ. 
        string image = data[2]?.Trim();
        
        if (!string.IsNullOrEmpty(image))
        {
            if(image.Equals("None")){
                characterImageManager.SetAllImageFalse();
            }else{
                characterImageManager.SetAllImageFalse();//ì¼ë‹¨ ëª¨ë“  ì´ë¯¸ì§€ êº¼ì£¼ê³ 
                string[] imagetoken = image.Split(",");
                List<string> imageNameToken = new List<string>();
                Queue<int> imagePosToken = new Queue<int>();//í í˜•íƒœë¡œ êº¼ë‚¸ë‹¤
                int Tempindex = 1;
                foreach(var token in imagetoken){
                    if(Tempindex%2 == 1){
                        imageNameToken.Add(token.Trim());
                        Tempindex++;
                        continue;
                    }
                    Debug.Log(token.Trim());
                    //í•˜ë“œì½”ë”©ì”ì¹˜
                    if(token.Trim() == "0000") imagePosToken.Enqueue(0b0000);
                    else if(token.Trim() == "0001") imagePosToken.Enqueue(0b0001);
                    else if(token.Trim() == "0010") imagePosToken.Enqueue(0b0010);
                    else if(token.Trim()== "0100") imagePosToken.Enqueue(0b0100);
                    else if(token.Trim() == "1000") imagePosToken.Enqueue(0b1000);
                    Debug.Log(imagePosToken.Count);
                    Tempindex++;
                }
                foreach(var name in imageNameToken){
                    characterImageManager.showCharcterImage(name, imagePosToken.Dequeue());
                }
            }
            
        }
        string se = data[3]?.Trim();
        // ğŸ”¹ íš¨ê³¼ìŒ ì¬ìƒ ì¬ìƒ
        if (!string.IsNullOrEmpty(se))
        {
            soundManager.SetCurrentSe(se);
            soundManager.PlayCurrentSe();
        }
        string voice = data[4]?.Trim();//ë³´ì´ìŠ¤(ë„£ì„ ìˆ˜ ìˆì„ì§€ë„?)
        if(!string.IsNullOrEmpty(voice)){
            soundManager.SetCurrentVoice(voice);//í˜„ì¬ ë³´ì´ìŠ¤ ì„¤ì •
            soundManager.PlayCurrentVoice();
        }
        string bgm = data[5]?.Trim();
        string background = data[6]?.Trim();
        if(!string.IsNullOrEmpty(background)){
            backGroundManager.SetCurrentBackground(background);

        }

        Debug.Log("bgmì´ë€ ì´ê²ƒ :" + bgm);
        // ğŸ”¹ ë°°ê²½ìŒì•…(BGM) ì¬ìƒ
        if (!string.IsNullOrEmpty(bgm))
        {
            soundManager.SetCurrentBgm(bgm);
            soundManager.PlayCurrentBgm();
        }
        string choiceField = data[7]?.Trim();  // ì„ íƒì§€ íŒŒì¼ëª…:ID (ê³µë°±ì´ë©´ ì„ íƒì§€ ì—†ìŒ)
        hasChoice = !string.IsNullOrEmpty(choiceField) ? true : false;//ì„ íƒì§€ê°€ ì¡´ì¬í•˜ëŠ”ì§€, ì¡´ì¬í•˜ì§€ ì•ŠëŠ”ì§€ ì²´í¬
        //ë§Œì•½ ì„ íƒì§€ ë¶€ë¶„ì´ ê³µë°±ì´ ì•„ë‹ˆë©´ ì—¬ê¸°ì„œ ì˜¤ë¥˜ ë‚  ê°€ëŠ¥ì„±ì´ ì¡´ì¬. 
        if (hasChoice)
        {
            //ì„ íƒì§€ê°€ ì¡´ì¬í•˜ë©´
            try
            {
                choiceManager.SetChoice(choiceField);//ì´ˆì´ìŠ¤ ë§¤ë‹ˆì €ì—ì„œ setchoiceë¡œ ì„¸íŒ…í•´ë³´ê¸°.
            }
            catch (FileDoesNotExistError)
            {
                //ë§Œì¼ ì¡´ì¬í•˜ì§€ë„ ì•ŠëŠ” ì´ë¦„ì˜ íŒŒì¼ì—ì„œ setchoiceí• ë¼ê³  í–ˆìœ¼ë©´
                Debug.LogError("ì €ê¸°ì„œ ë°›ì€ ì—ëŸ¬ ê·¸ëŒ€ë¡œ ì—¬ê¸°ì—ì„œê¹Œì§€ ë°›ëŠ”ë‹¤.");
                return;//ì—ëŸ¬ ë–´ìœ¼ë‹ˆ ë¦¬í„´
            }
        }
        else
        {
            Debug.Log("âœ… ì´ ë¼ì¸ì—ì„  ì„ íƒì§€ê°€ ì—†ìŒ.");
        }
        if(data.Length >=9&&!data[8].Trim().Equals("None")){
            Debug.Log("ë°ì´í„°" + data[8] + !data[8].Equals("None"));
            string Animation = data[8]?.Trim();
            StartAnimation(Animation);
        }
        

        //ëª¨ë“  ì •ë³´ê°€ ê°–ì¶°ì¡Œë‹¤. 
        Debug.Log($"âœ… ëŒ€ì‚¬ ì •ë³´ - í™”ì: {speaker}, ëŒ€ì‚¬: {dialogue}, ì„ íƒì§€ ë°ì´í„°: {choiceField}");

        isDialogueReady = true;//í…ìŠ¤íŠ¸ ì¤€ë¹„ ì´í›„ í‚¤ê¸°

        // ğŸ”¹ í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰ (ë„ì¤‘ `%` íƒœê·¸ë¥¼ ë§Œë‚˜ë©´ ì„ íƒì§€ íŒ¨ë„ í˜¸ì¶œ)
        TextAnimationCor = TypeText(dialogue);
        StartCoroutine(TextAnimationCor);//ì „ë‹¬
    }

    public void ShowNextLineAfterChoice()
    {
        isDialogueReady = false;
        isChoicePanelActive = false;//ì—¬ê¸°ë§Œ ì •ìƒí™”í•´ì¤˜ë„ ì•Œì•„ì„œ êµ´ëŸ¬ê°. 
        currentIndex++;
        ShowNextLine();


    }

    /// <summary>
    /// í…ìŠ¤íŠ¸ íƒ€ì´í•‘ ì• ë‹ˆë©”ì´ì…˜ì´ ë‹¤ ëë‚¬ì„ë•Œ ì´ê±¸ë¡œ ë°›ì•„ì˜´
    /// </summary>
    /// <param name="choiceIndex"></param>
    private void onCompleteTyping()
    {
        Debug.Log($"âœ… ëŒ€ì‚¬ ì¶œë ¥ ì™„ë£Œ (currentIndex: {currentIndex})");
        if(isTrandition){
            transitionControllerobj.SetActive(false);
            isTrandition = false;
        }
        if (hasChoice)
        {
            Debug.Log($"âœ… ì„ íƒì§€ íŒ¨ë„ í˜¸ì¶œ ì¤€ë¹„ - ë‹¤ì´ì–¼ë¡œê·¸ ë§¤ë‹ˆì €");
            isChoicePanelActive = true;
            choiceManager.StartChoice();
        }
        else
        {
            isTyping = false;
            Debug.Log("âœ… ì„ íƒì§€ê°€ ì—†ìŒ. í‚¤ ì…ë ¥ ëŒ€ê¸° ì¤‘.");
        }

    }

    /*[í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ë¶€ë¶„]*/
    private static readonly Regex tagRegex = new Regex(@"[\\$@#*%^]-?\d+(\.\d+)?|\(end\)", RegexOptions.Compiled);
    private string RemoveTags(string input)
    {
        return tagRegex.Replace(input, "");
    }
    IEnumerator TypeText(string fullText)
    {
        isTyping = true; // íƒ€ì´í•‘ ì¤‘ì¸ ìƒíƒœ
        Debug.Log(fullText);
        DialogueText.text = "";

        /*[í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ê´€ë ¨ ë³€ìˆ˜]*/
        float currentDelay = defaultDelay;
        remainTextAmout = fullText.Length;

        // ğŸ”¥ í˜„ì¬ ì„¤ì •ëœ ë³´ì´ìŠ¤ íŒŒì¼ì´ ìˆë‹¤ë©´ ìë™ ì¬ìƒ
        string currentVoice = soundManager.GetCurrentVoiceFile();
        if (!string.IsNullOrEmpty(currentVoice))
        {
            Debug.Log($"ğŸ¤ ë³´ì´ìŠ¤ ì¬ìƒ: {currentVoice}");
            soundManager.PlayCurrentVoice();
        }

        // ğŸ”¥ íŠ¹ìˆ˜ íƒœê·¸ë¥¼ ë¨¼ì € ì œê±°í•˜ì—¬ í´ë¦°í•œ í…ìŠ¤íŠ¸ ì¶”ì¶œ
        string cleanText = RemoveAllTags(fullText);

        for (int i = 0; i < cleanText.Length; i++)
        {
            char c = cleanText[i];

            // í•œ ê¸€ìì”© ì¶œë ¥
            DialogueText.text += c;
            remainTextAmout--;

            soundManager.PlayCurrentVoice();
            

            yield return new WaitForSeconds(currentDelay);
        }

        isTyping = false;
        onCompleteTyping();
    }

    /// <summary>
    /// ëŒ€ì‚¬ì—ì„œ ë¶ˆí•„ìš”í•œ íƒœê·¸ë¥¼ ì œê±°í•˜ì—¬ í´ë¦°í•œ í…ìŠ¤íŠ¸ë¥¼ ë°˜í™˜í•©ë‹ˆë‹¤.
    /// </summary>
    private string RemoveAllTags(string fullText)
    {
        // ğŸ”¹ íŠ¹ìˆ˜ íƒœê·¸ íŒ¨í„´ ì •ì˜ (Regex í™œìš©)
        string pattern = @"[\\$@#*%^]-?\d+(\.\d+)?|\(end\)";

        // ğŸ”¥ ì •ê·œì‹ì„ ì‚¬ìš©í•˜ì—¬ ëª¨ë“  íƒœê·¸ ì œê±°
        return Regex.Replace(fullText, pattern, "");
    }

    public string RemoveAllTag(string fullText)
    {
        string allText = "";
        for (int i = 0; i < fullText.Length; i++)
        {
            char c = fullText[i];
            if (c == '\\')
                //í•˜ë‚˜ ì´ìŠ¤ì¼€ì´í”„ ë¬¸ìì˜€êµ¬ë‚˜
                {
                    // ì—¬ê¸´ ì•ˆì „í•œ ê³³ì´ì—ìš”.\2 <- ì´ ë¶€ë¶„ì— í•´ë‹¹
                    int endIdx = i + 1;
                    int digitLength = 0;//ê¸¸ì´ íŒì •.
                    while (endIdx < fullText.Length && !string.Equals("(end)", fullText.Substring(endIdx, 5)))
                    {
                        //íƒœê·¸ê°€ ëë‚  ë•Œê¹Œì§€
                        endIdx++;//ì¼ë‹¨ ì¸ë±ìŠ¤ ë†€ë¦¬ê³ 
                        digitLength++;
                        if (endIdx == fullText.Length)
                        {
                            Debug.LogError($"{fullText} ë¶€ë¶„ì— \\ íƒœê·¸ ì²˜ë¦¬ë¥¼ ì˜ëª»í•˜ì…¨ìŠµë‹ˆë‹¤. (end)ê°€ ì—†ìŠµë‹ˆë‹¤");
                        }
                    }
                    i = endIdx + 4;
                    continue;
                }

                // ëŒ€ê¸° ($ìˆ«ì)
                if (c == '$')
                {
                    int endIdx = i + 1;
                    int digitLength = 0;//ê¸¸ì´ íŒì •.
                    while (endIdx < fullText.Length && !fullText.Substring(endIdx, 5).Equals("(end)"))
                    {
                        endIdx++;
                        digitLength++;
                        if (endIdx == fullText.Length)
                        {
                            Debug.LogError($"{fullText} ë¶€ë¶„ì— $ íƒœê·¸ ì²˜ë¦¬ë¥¼ ì˜ëª»í•˜ì…¨ìŠµë‹ˆë‹¤. (end)ê°€ ì—†ìŠµë‹ˆë‹¤");
                        }
                    }

                    i = endIdx + 4;
                    continue;
                }

                // í¬ê¸° ë³€ê²½ (@ìˆ«ì)
                if (c == '@')
                {
                    int endIdx = i + 1;
                    int digitLength = 0;//ê¸¸ì´ íŒì •.
                    while (endIdx < fullText.Length && !fullText.Substring(endIdx, 5).Equals("(end)"))
                    {
                        endIdx++;
                        digitLength++;
                        if (endIdx == fullText.Length)
                        {
                            Debug.LogError($"{fullText} ë¶€ë¶„ì— @ íƒœê·¸ ì²˜ë¦¬ë¥¼ ì˜ëª»í•˜ì…¨ìŠµë‹ˆë‹¤. (end)ê°€ ì—†ìŠµë‹ˆë‹¤");
                        }
                    }

                    i = endIdx + 4;
                    continue;
                }

                // ë³´ì´ìŠ¤ í”¼ì¹˜ ë³€ê²½ (#ìˆ«ì)
                if (c == '#')
                {
                    int endIdx = i + 1;
                    while (endIdx < fullText.Length && !fullText.Substring(endIdx, 5).Equals("(end)"))
                    {
                        endIdx++;
                        if (endIdx == fullText.Length)
                        {
                            Debug.LogError($"{fullText} ë¶€ë¶„ì— # íƒœê·¸ ì²˜ë¦¬ë¥¼ ì˜ëª»í•˜ì…¨ìŠµë‹ˆë‹¤. (end)ê°€ ì—†ìŠµë‹ˆë‹¤");
                        }
                    }

                    i = endIdx + 4;//end ê±´ë„ˆë›°ê¸°
                    continue;
                }


                // ë³´ì´ìŠ¤ ë³¼ë¥¨ ë³€ê²½ (*ìˆ«ì)
                if (c == '*')
                {
                    int endIdx = i + 1;
                    while (endIdx < fullText.Length && !fullText.Substring(endIdx, 5).Equals("(end)"))
                    {
                        endIdx++;
                        if (endIdx == fullText.Length)
                        {
                            Debug.LogError($"{fullText} ë¶€ë¶„ì— * íƒœê·¸ ì²˜ë¦¬ë¥¼ ì˜ëª»í•˜ì…¨ìŠµë‹ˆë‹¤. (end)ê°€ ì—†ìŠµë‹ˆë‹¤");
                        }
                    }
                    i = endIdx + 4;////end ê±´ë„ˆë›°ê¸°
                    continue;
                }

                // ì„ íƒì§€ (%n) ë˜ëŠ” ë„ë• (^n)
                if (c == '%' || c == '^')
                {
                    continue;
                }

                // í•œ ê¸€ìì”© ì¶œë ¥
                allText += c;

        }
        return allText;

    }


    public void StartAnimation(string animeName){
        switch(animeName){
            case "CircleFadeIn":
                isTrandition = true;
                transitionShaderController.StartFadeIn();
                
                break;
            case "CircleFadeOut":
                isTrandition = true;
                transitionShaderController.StartFadeOut();
          
                break;
            default:
                Debug.LogError("ì •ì˜ë˜ì§€ ì•Šì€ ì• ë‹ˆë©”ì´ì…˜ì…ë‹ˆë‹¤");
                break;
        }
        
    }


    //íƒœí¬ë‹ˆì»¬í•œ ë©”ì„œë“œë“¤
    public int GetCurrentIndex()
    {
        return currentIndex;
    }

    public void SetCurrentIndex(int newIndex)
    {
        currentIndex = newIndex;
    }


    /*[í…Œí¬ë‹ˆì»¬í•œ ë©”ì„œë“œë“¤ ëª¨ìŒì…ë‹ˆë‹¤]*/


    /// <summary>
    /// ë‹¤ì´ì–¼ë¡œê·¸ ë§¤ë‹ˆì €ì˜ íŒŒì¼ ë³€ê²½ ë¡œì§ì…ë‹ˆë‹¤. ë§Œì¼ íŒŒì¼ì´ ì—†ì„ ê²½ìš° ì˜ˆì™¸ë¥¼ ë˜ì§‘ë‹ˆë‹¤.
    /// </summary>
    /// <param name="fileName">ì´ ì´ë¦„ì„ ê°€ì§„ íŒŒì¼ì„ ì°¾ìŠµë‹ˆë‹¤</param>
    /// <param name="index">ì„¤ì •í•˜ê¸¸ ì›í•˜ëŠ” ì¸ë±ìŠ¤ì…ã„´ë””ã…. </param>
    public void changeDialogueTextFile(string fileName, int index)
    {
        try
        {
            fileManager.SetCurrentFile(fileName);
            SetCurrentIndex(index);//ì¸ë±ìŠ¤ ì¬ì„¤ì •.

        }
        catch (FileDoesNotExistError e)
        {
            Debug.LogError(e.Message);
            throw e;
        }

    }







    //[ë ˆê±°ì‹œë“¤(ê³¼ê±° ì”ì¬)]
    private void OnTriggerTyping()
    {
        // ğŸ¯ **í…ìŠ¤íŠ¸ ì• ë‹ˆë©”ì´ì…˜ ë„ì¤‘ `%` íƒœê·¸ë¥¼ ë§Œë‚˜ë©´ ì¦‰ì‹œ ì„ íƒì§€ë¥¼ ë„ìš°ê¸° ìœ„í•œ ë¶€ë¶„**
        //ê·¼ë° í•„ìš” ì—†ì„ë“¯í•¨. í•œ ì¤„ë‹¹ ì•¡ì…˜ì„ ì·¨í•˜ëŠ”ê±¸ë¡œ í•¨. 
        //ë ˆê±°ì‹œ ë¶„ë¥˜ ì‚¬ìœ  : í…ìŠ¤íŠ¸ ì¶œë ¥ ë„ì¤‘ ì„ íƒì§€ë¥¼ ë„ì›Œì•¼ í•  ê²½ìš°ëŠ” ì—†ìœ¼ë¯€ë¡œ. 
        // if (hasChoice)
        // {
        //     Debug.Log("ğŸ¯ % íƒœê·¸ ê°ì§€ë¨ â†’ ì„ íƒì§€ íŒ¨ë„ ì¦‰ì‹œ ë„ìš°ê¸°");
        //     StartCoroutine(ShowChoicePanel(choiceFile, choiceID));
        //     isChoicePanelActive = true;
        // }

    }
    public void OnChoiceSelected(string nextFile, int nextIndex)
    {
        //[íê¸° ì‚¬ìœ ]
        //íŒŒì¼ ë³€ê²½ì´ ì—†ëŠ” ë¡œì§ìœ¼ë¡œ ì‘ì„±ì¤‘ì´ê¸° ë•Œë¬¸ì— ë”±íˆ ì‚¬ìš©í•  ì¼ì´ ì—†ìŒ.
        // Debug.Log($"ğŸ“‚ OnChoiceSelected í˜¸ì¶œë¨: nextFile = {nextFile}, nextIndex = {nextIndex}");

        // if (!string.IsNullOrEmpty(nextFile))
        // {
        //     fileManager.SetCurrentFile(nextFile);
        //     currentIndex = nextIndex-1; // ë‹¤ìŒ ì¸ë±ìŠ¤ë¡œ ì´ë™

        // }
        // else
        // {
        //     Debug.Log("âœ… ë‹¤ìŒ íŒŒì¼ì´ ì—†ìŒ. í˜„ì¬ íŒŒì¼ ìœ ì§€í•˜ê³  ë‹¤ìŒ ëŒ€ì‚¬ ì¶œë ¥.");
        //     currentIndex = nextIndex-1; // ê¸°ì¡´ íŒŒì¼ì—ì„œ ë‹¤ìŒ ì¸ë±ìŠ¤ë¡œ ì´ë™

        // }

        // isChoicePanelActive = false;
        // isWaitingForText = false;

        // ShowNextLine();
    }
    /// <summary>
    /// ëŒ€ì‚¬ í…ìŠ¤íŠ¸ì˜ íƒœê·¸ë¥¼ ì œê±°í•©ë‹ˆë‹¤. 
    /// </summary>
    /// <param name="dialogue">ëŒ€ì‚¬ í…ìŠ¤íŠ¸ì…ë‹ˆë‹¤.</param>
    private void RemoveDialogueTag(string dialogue)
    {
        //íƒœê·¸ ì œê±° ê¸°ëŠ¥ì„ ë°–ìœ¼ë¡œ ë¹¼ë†“ìŒ. 

        // ğŸ”¹ `^` ê¸°í˜¸ ì œê±°
        if (dialogue.Contains("^"))
        {
            dialogue = dialogue.Replace("^", ""); // `^` íƒœê·¸ ì œê±°
            Debug.Log("âœ… ë„ë• íƒœê·¸(^): ì œê±°ë¨");
        }
        // ğŸ”¹ `%` íƒœê·¸ ì œê±° ë° ì„ íƒì§€ ì—¬ë¶€ í™•ì¸
        hasChoice = dialogue.Contains("%");
        if (hasChoice)
        {
            dialogue = dialogue.Replace("%", ""); // `%` íƒœê·¸ ì œê±°
            Debug.Log("âœ… ì„ íƒì§€ íƒœê·¸(%): ì„ íƒì§€ ìˆìŒ");
        }
    }

}